---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    #ports:
      #- "192.168.0.111:32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt/share/MEDIA/:/mnt/media 
      #- /mnt/share/CloudData/DockerData/plex/plex_config:/config
      - /opt/PlexLibrary/:/config

    restart: unless-stopped
