---
version: "2.1"
services:
  plex:
    image: .
    container_name: plex
    network_mode: host
    env_file:
      - .env
    volumes:
      - /mnt/share/MEDIA/:/mnt/media 
    restart: unless-stopped